from _typeshed import Incomplete
from threading import local as Local

UTC: Incomplete

class _LocalStack(Local):
    def __init__(self) -> None: ...
    def __iter__(self): ...
    def push(self, resource) -> None: ...
    def pop(self): ...
    @property
    def top(self): ...

def make_secure_channel(credentials, user_agent, host, extra_options=()): ...
def make_secure_stub(credentials, user_agent, stub_class, host, extra_options=()): ...
def make_insecure_stub(stub_class, host, port: Incomplete | None = None): ...
