from _typeshed import Incomplete
from google.api_core import retry_async as retries
from google.cloud.firestore_v1.base_batch import BaseWriteBatch

class AsyncWriteBatch(BaseWriteBatch):
    def __init__(self, client) -> None: ...
    write_results: Incomplete
    commit_time: Incomplete
    async def commit(self, retry: retries.AsyncRetry | object | None = ..., timeout: float | None = None) -> list: ...
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc_value, traceback) -> None: ...
