import google.cloud.firestore_v1.types.query_profile as query_profile_pb
from google.cloud.firestore_v1.query_profile import ExplainMetrics, ExplainOptions as ExplainOptions
from typing import Any, AsyncGenerator, Coroutine, TypeVar

T = TypeVar('T')

class AsyncStreamGenerator(AsyncGenerator[T, Any]):
    def __init__(self, response_generator: AsyncGenerator[T | query_profile_pb.ExplainMetrics, Any], explain_options: ExplainOptions | None = None) -> None: ...
    def __aiter__(self) -> AsyncGenerator[T, Any]: ...
    async def __anext__(self) -> T: ...
    def asend(self, value: Any = None) -> Coroutine[Any, Any, T]: ...
    def athrow(self, *args, **kwargs) -> Coroutine[Any, Any, T]: ...
    def aclose(self): ...
    @property
    def explain_options(self) -> ExplainOptions | None: ...
    async def get_explain_metrics(self) -> ExplainMetrics: ...
