from _typeshed import Incomplete
from google.api_core import retry_async as retries
from google.cloud.firestore_v1 import _helpers
from google.cloud.firestore_v1.base_document import BaseDocumentReference, DocumentSnapshot
from google.cloud.firestore_v1.types import write as write
from google.protobuf.timestamp_pb2 import Timestamp as Timestamp
from typing import AsyncGenerator, Iterable

logger: Incomplete

class AsyncDocumentReference(BaseDocumentReference):
    def __init__(self, *path, **kwargs) -> None: ...
    async def create(self, document_data: dict, retry: retries.AsyncRetry | object | None = ..., timeout: float | None = None) -> write.WriteResult: ...
    async def set(self, document_data: dict, merge: bool = False, retry: retries.AsyncRetry | object | None = ..., timeout: float | None = None) -> write.WriteResult: ...
    async def update(self, field_updates: dict, option: _helpers.WriteOption | None = None, retry: retries.AsyncRetry | object | None = ..., timeout: float | None = None) -> write.WriteResult: ...
    async def delete(self, option: _helpers.WriteOption | None = None, retry: retries.AsyncRetry | object | None = ..., timeout: float | None = None) -> Timestamp: ...
    async def get(self, field_paths: Iterable[str] | None = None, transaction: Incomplete | None = None, retry: retries.AsyncRetry | object | None = ..., timeout: float | None = None) -> DocumentSnapshot: ...
    async def collections(self, page_size: int | None = None, retry: retries.AsyncRetry | object | None = ..., timeout: float | None = None) -> AsyncGenerator: ...
