from _typeshed import Incomplete
from google.api_core import retry as retries
from google.cloud.firestore_v1.base_batch import BaseWriteBatch

class WriteBatch(BaseWriteBatch):
    def __init__(self, client) -> None: ...
    write_results: Incomplete
    commit_time: Incomplete
    def commit(self, retry: retries.Retry | object | None = ..., timeout: float | None = None) -> list: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
