from google.cloud.firestore_v1.query_profile import ExplainMetrics, ExplainOptions as ExplainOptions
from typing import Any, Generator, TypeVar

T = TypeVar('T')

class StreamGenerator(Generator[T, Any, ExplainMetrics | None]):
    def __init__(self, response_generator: Generator[T, Any, ExplainMetrics | None], explain_options: ExplainOptions | None = None) -> None: ...
    def __iter__(self) -> StreamGenerator: ...
    def __next__(self) -> T: ...
    def send(self, value: Any = None) -> T: ...
    def throw(self, *args, **kwargs) -> T: ...
    def close(self): ...
    @property
    def explain_options(self) -> ExplainOptions | None: ...
    def get_explain_metrics(self) -> ExplainMetrics: ...
