from _typeshed import Incomplete

class Sentinel:
    description: Incomplete
    def __init__(self, description) -> None: ...
    def __copy__(self): ...
    def __deepcopy__(self, memo): ...

DELETE_FIELD: Incomplete
SERVER_TIMESTAMP: Incomplete

class _ValueList:
    slots: Incomplete
    def __init__(self, values) -> None: ...
    def __eq__(self, other): ...
    @property
    def values(self): ...

class ArrayUnion(_ValueList): ...
class ArrayRemove(_ValueList): ...

class _NumericValue:
    def __init__(self, value) -> None: ...
    @property
    def value(self): ...
    def __eq__(self, other): ...

class Increment(_NumericValue): ...
class Maximum(_NumericValue): ...
class Minimum(_NumericValue): ...
