import collections
from typing import Sequence

class Vector(collections.abc.Sequence):
    def __init__(self, value: Sequence[float]) -> None: ...
    def __getitem__(self, arg): ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def to_map_value(self): ...
