from _typeshed import Incomplete

class _Monkey:
    module: Incomplete
    to_restore: Incomplete
    def __init__(self, module, **kw) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...

class _NamedTemporaryFile:
    def __init__(self, suffix: str = '') -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...

class _GAXBaseAPI:
    def __init__(self, **kw) -> None: ...

class _GAXPageIterator:
    page_token: Incomplete
    def __init__(self, *pages, **kwargs) -> None: ...
    def __next__(self): ...
