from .transports.base import FirestoreTransport
from _typeshed import Incomplete
from google.api_core import gapic_v1
from google.api_core.client_options import ClientOptions
from google.auth import credentials as ga_credentials
from google.cloud.firestore_v1.services.firestore import pagers
from google.cloud.firestore_v1.types import common, document, document as gf_document, firestore, write as gf_write
from google.longrunning import operations_pb2
from typing import AsyncIterable, AsyncIterator, Awaitable, Callable, MutableSequence, Sequence

__all__ = ['FirestoreAsyncClient']

class FirestoreAsyncClient:
    DEFAULT_ENDPOINT: Incomplete
    DEFAULT_MTLS_ENDPOINT: Incomplete
    common_billing_account_path: Incomplete
    parse_common_billing_account_path: Incomplete
    common_folder_path: Incomplete
    parse_common_folder_path: Incomplete
    common_organization_path: Incomplete
    parse_common_organization_path: Incomplete
    common_project_path: Incomplete
    parse_common_project_path: Incomplete
    common_location_path: Incomplete
    parse_common_location_path: Incomplete
    @classmethod
    def from_service_account_info(cls, info: dict, *args, **kwargs): ...
    @classmethod
    def from_service_account_file(cls, filename: str, *args, **kwargs): ...
    from_service_account_json = from_service_account_file
    @classmethod
    def get_mtls_endpoint_and_cert_source(cls, client_options: ClientOptions | None = None): ...
    @property
    def transport(self) -> FirestoreTransport: ...
    @property
    def api_endpoint(self): ...
    @property
    def universe_domain(self) -> str: ...
    get_transport_class: Incomplete
    def __init__(self, *, credentials: ga_credentials.Credentials | None = None, transport: str | FirestoreTransport | Callable[..., FirestoreTransport] | None = 'grpc_asyncio', client_options: ClientOptions | None = None, client_info: gapic_v1.client_info.ClientInfo = ...) -> None: ...
    async def get_document(self, request: firestore.GetDocumentRequest | dict | None = None, *, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> document.Document: ...
    async def list_documents(self, request: firestore.ListDocumentsRequest | dict | None = None, *, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> pagers.ListDocumentsAsyncPager: ...
    async def update_document(self, request: firestore.UpdateDocumentRequest | dict | None = None, *, document: gf_document.Document | None = None, update_mask: common.DocumentMask | None = None, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> gf_document.Document: ...
    async def delete_document(self, request: firestore.DeleteDocumentRequest | dict | None = None, *, name: str | None = None, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> None: ...
    def batch_get_documents(self, request: firestore.BatchGetDocumentsRequest | dict | None = None, *, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> Awaitable[AsyncIterable[firestore.BatchGetDocumentsResponse]]: ...
    async def begin_transaction(self, request: firestore.BeginTransactionRequest | dict | None = None, *, database: str | None = None, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> firestore.BeginTransactionResponse: ...
    async def commit(self, request: firestore.CommitRequest | dict | None = None, *, database: str | None = None, writes: MutableSequence[gf_write.Write] | None = None, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> firestore.CommitResponse: ...
    async def rollback(self, request: firestore.RollbackRequest | dict | None = None, *, database: str | None = None, transaction: bytes | None = None, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> None: ...
    def run_query(self, request: firestore.RunQueryRequest | dict | None = None, *, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> Awaitable[AsyncIterable[firestore.RunQueryResponse]]: ...
    def run_aggregation_query(self, request: firestore.RunAggregationQueryRequest | dict | None = None, *, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> Awaitable[AsyncIterable[firestore.RunAggregationQueryResponse]]: ...
    async def partition_query(self, request: firestore.PartitionQueryRequest | dict | None = None, *, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> pagers.PartitionQueryAsyncPager: ...
    def write(self, requests: AsyncIterator[firestore.WriteRequest] | None = None, *, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> Awaitable[AsyncIterable[firestore.WriteResponse]]: ...
    def listen(self, requests: AsyncIterator[firestore.ListenRequest] | None = None, *, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> Awaitable[AsyncIterable[firestore.ListenResponse]]: ...
    async def list_collection_ids(self, request: firestore.ListCollectionIdsRequest | dict | None = None, *, parent: str | None = None, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> pagers.ListCollectionIdsAsyncPager: ...
    async def batch_write(self, request: firestore.BatchWriteRequest | dict | None = None, *, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> firestore.BatchWriteResponse: ...
    async def create_document(self, request: firestore.CreateDocumentRequest | dict | None = None, *, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> document.Document: ...
    async def list_operations(self, request: operations_pb2.ListOperationsRequest | None = None, *, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> operations_pb2.ListOperationsResponse: ...
    async def get_operation(self, request: operations_pb2.GetOperationRequest | None = None, *, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> operations_pb2.Operation: ...
    async def delete_operation(self, request: operations_pb2.DeleteOperationRequest | None = None, *, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> None: ...
    async def cancel_operation(self, request: operations_pb2.CancelOperationRequest | None = None, *, retry: OptionalRetry = ..., timeout: float | object = ..., metadata: Sequence[tuple[str, str]] = ()) -> None: ...
    async def __aenter__(self) -> FirestoreAsyncClient: ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...
